### ISSUE TITLE
Bunnies have wrong health

### ISSUE THREAD

**Issue by Stenodyon** [bunny-defense/bunny_defense#1]
In singleplayer (haven't tested multiplayer) some bunnies have the wrong health (heavy bunnies start at half their max health, fast bunnies start at 1.5x their max health).

**Comment by Gu1nness** [comment]
Wtf ?
This is supposed to be hardcoded in the rabbits definition no ?

For example [this line](https://github.com/Stenodyon/bunny_defense/blob/network/src/main/scala/game_mechanics/bunny/heavybunny.scala#L19) should be its base hp.

To be checked...

**Comment by Gu1nness** [comment]
In fact I think I have found out what is happening.
Bunnies have ```initial_hp``` and ```hp``` attributes ([see here](https://github.com/Stenodyon/bunny_defense/blob/network/src/main/scala/game_mechanics/bunny/bunny.scala#L30).

However, the attribute is never overriden in the definition of other bunnies.
I'll fix it soon.

**Comment by Stenodyon** [comment]
Fixed in 1fb4aab68a1388bf3f1372ff894b173aac04c630
